trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install NodeJS
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Install Playwright browsers
- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

# Run Playwright tests
- script: |
    npx playwright test
  displayName: 'Run Playwright tests'

# âœ… Publish Playwright JUnit result to Azure Test tab
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'Playwright Automation Test Run'
  displayName: 'Publish Playwright Test Results'

# Publish Playwright HTML Report
- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: playwright-report
    artifact: playwright-report
  displayName: 'Publish Playwright HTML Report'